---
title: "Heart rate plot"
fontsize: 12pt
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 2

---

```{r, echo = FALSE}
  p('Heart rate is the speed of the heartbeat measured by the number of contractions (beats)
  of the heart per minute (bpm). The heart rate can vary according to the body\'s physical needs,
  including the need to absorb oxygen and excrete carbon dioxide, but is also modulated by numerous
  factors, including, but not limited to, genetics, physical fitness, stress or psychological status,
  diet, drugs, hormonal status, environment, and disease/illness as well as the interaction between
  and among these factors.', br(), br(),
  'You can insert your usual heart rate for each of the age intervals anc compare with the average american
  heart rata:')
  br()
  p(strong(h3('How can you know your heart rate?')))
  br()
  p('At the wrist, lightly press the index and middle fingers of one hand on the opposite wrist,
  just below the base of the thumb.',br(), 'At the neck, lightly press the side of the neck,
  just below your jawbone', br(), 'Count the number of beats in 15 seconds, and multiply by four.
  That\'s your heart rate.',br())
```

## Here is the interactive heart rate plot:

```{r fig.width = 4, fig.height = 3, echo = FALSE, results = "hold"}

lb <- linked_brush()
lb$input(
        heart_plot %>%
                set_options(width = 1000, height = 600)
)
```